# Generated by Django 5.2.5 on 2025-09-10 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='SQLFile',
            new_name='File',
        ),
    ]
